In [1]:
import pandas as pd
import numpy as np
import itertools
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer, HashingVectorizer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import PassiveAggressiveClassifier
from sklearn.naive_bayes import MultinomialNB
from sklearn import metrics
import matplotlib.pyplot as plt

In [7]:
dataset=pd.read_csv('cluster.csv', index_col=None)

In [8]:
dataset

text  label
0     im feeling rather rotten so im not very ambiti...      0
1             im updating my blog because i feel shitty      0
2     i never make her separate from me because i do...      0
3     i left with my bouquet of red and yellow tulip...      1
4       i was feeling a little vain when i did this one      0
...                                                 ...    ...
1995  i just keep feeling like someone is being unki...      3
1996  im feeling a little cranky negative after this...      3
1997  i feel that i am useful to my people and that ...      1
1998  im feeling more comfortable with derby i feel ...      1
1999  i feel all weird when i have to meet w people ...      4

[2000 rows x 2 columns]

In [9]:
y=dataset["label"]

In [10]:
X_train, X_test, y_train, y_test = train_test_split(dataset['text'], y, test_size=0.33, random_state=53)

In [11]:
count_vectorizer = CountVectorizer(stop_words='english')
count_train = count_vectorizer.fit_transform(X_train)
print(count_train)
count_test = count_vectorizer.transform(X_test)

  (0, 908)	1
  (0, 1745)	1
  (0, 1158)	3
  (0, 3056)	1
  (0, 2671)	1
  (0, 479)	1
  (0, 1024)	1
  (0, 1319)	1
  (1, 1158)	1
  (1, 2671)	1
  (1, 1854)	1
  (1, 3089)	1
  (1, 759)	1
  (1, 2026)	1
  (1, 825)	1
  (2, 1158)	1
  (2, 629)	1
  (2, 2092)	1
  (2, 1460)	1
  (3, 1745)	1
  (3, 1158)	1
  (3, 336)	1
  (3, 1136)	1
  (4, 1712)	1
  (4, 1159)	1
  :	:
  (1335, 358)	1
  (1335, 2516)	1
  (1335, 3269)	1
  (1336, 1158)	1
  (1336, 2992)	1
  (1336, 286)	1
  (1337, 1158)	1
  (1337, 759)	1
  (1337, 1034)	1
  (1337, 734)	1
  (1338, 1158)	1
  (1338, 759)	1
  (1338, 3408)	1
  (1338, 1166)	1
  (1338, 2918)	1
  (1338, 318)	1
  (1339, 1159)	1
  (1339, 3408)	1
  (1339, 2109)	1
  (1339, 3480)	1
  (1339, 2895)	1
  (1339, 1472)	1
  (1339, 776)	1
  (1339, 2847)	1
  (1339, 3057)	1


In [12]:
dir(count_train)

['A',
 'H',
 'T',
 '__abs__',
 '__add__',
 '__array_priority__',
 '__bool__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__div__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__idiv__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__le__',
 '__len__',
 '__lt__',
 '__matmul__',
 '__module__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__nonzero__',
 '__pow__',
 '__radd__',
 '__rdiv__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rmatmul__',
 '__rmul__',
 '__round__',
 '__rsub__',
 '__rtruediv__',
 '__setattr__',
 '__setitem__',
 '__sizeof__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__truediv__',
 '__weakref__',
 '_add_dense',
 '_add_sparse',
 '_arg_min_or_max',
 '_arg_min_or_max_axis',
 '_ascontainer',
 '_asfptype',
 '_asindices',
 '_binopt',
 '_bsr_container',
 '_container',
 '_coo_container',
 '_cs_matrix__ge

In [13]:
len(count_vectorizer.get_feature_names_out())

3549

In [14]:
print(count_train.toarray())

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [16]:
clf = MultinomialNB()

clf.fit(count_train, y_train)
pred = clf.predict(count_test)
score = metrics.accuracy_score(y_test, pred)
print("accuracy:   %0.3f" % score)

cm = metrics.confusion_matrix(y_test, pred, labels=['0','1','2','3','4',])

accuracy:   0.598


In [17]:
from sklearn.metrics import classification_report

report=classification_report(y_test, pred)

C:\Users\Hxtreme\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Hxtreme\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Hxtreme\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [18]:
print(report)

              precision    recall  f1-score   support

           0       0.58      0.81      0.67       195
           1       0.59      0.86      0.70       223
           2       0.86      0.11      0.20        54
           3       0.68      0.31      0.43        84
           4       0.83      0.19      0.31        80
           5       0.00      0.00      0.00        24

    accuracy                           0.60       660
   macro avg       0.59      0.38      0.38       660
weighted avg       0.63      0.60      0.54       660

